# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca137bbeb95acbe0c0200a4e7ca36aa71105f9acc3d9a72d99f2cf1601c3936570585b09b25e09723ba272a070ddbc8f8a2e7fd644ff6f5ec2a5072794d9826f

test:
  secret_key_base: 3ed6c861e8a02aed1c495dadedfc55fa8c4b0e80bbbf35d4f6873a88df632e44d6c4cacd4960c586e9e547e8194663f46c2d1ec39a5b29c2195bb86987ff9966

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
